language: python

python:
  # We don't actually use the Travis Python, but this keeps it organized.
  # - "3.5"
  - "3.6"

os:
  - linux
  - osx

install:
  - sudo apt-get update
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

  # Replace dep1 dep2 ... with your dependencies
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION numpy scipy matplotlib shapely pytest
  - source activate test-environment
  - conda install -c amoodie rivers2stratigraphy
  - hash -r

script:
  - python3 import_test.py
  - which -a pytest
  - pytest
  # Your test script goes here

# sudo: false
# filter_secrets: false

# before_install:
# install:
